### ISSUE TITLE
Soapfish wsdl2py Error

### ISSUE THREAD

**Issue by gudddu** [FelixSchwarz/soapfish#45] opened 2015-01-17 18:54 UTC
I downloaded the ZIP (soapfish-master.zip) from https://github.com/FelixSchwarz/soapfish

I am on Windows 7 and Python 2.7

I am getting relative imports error when executing wsdl2py

>D:\Projects\SOAP\soapfish\>python C:\Python27\Lib\site-packages\soapfish-0.6dev-py2.7.egg\soapfish\wsdl2py.py -c Doc.wsdl
>Traceback (most recent call last):
>File "C:\Python27\Lib\site-packages\soapfish-0.6dev-py2.7.egg\soapfish\wsdl2py.py", line 16, in module
>from .soap import SOAP_HTTP_Transport, SOAPVersion
>ValueError: Attempted relative import in non-package`

So i had to replace at all places where relative import was done

>from .soap import SOAP_HTTP_Transport, SOAPVersion
>to
>from soap import SOAP_HTTP_Transport, SOAPVersion

and 

>from . import namespaces as ns
>to
>import namespaces as ns

and likewise.

Following that, the wsdl2py command gives this error. The WSDL I am working with is at http://dpaste.com/2XP4NP6

The Traceback is at http://dpaste.com/1KH7W99 (not pasting in the body of the issue as the markdown is messing it up)

Regards,
Guddu

**Comment by FelixSchwarz** [comment] 2016-01-26 22:19
iurisilvio added a lot of missing features in soapfish in the last months so I wanted to give your WSDL a try but unfortunately the links are dead. Would you mind uploading the WSDL again?

**Comment by pope1ni** [comment] 2016-01-28 16:49
This seems strange to me. The exception `ValueError: Attempted relative import in non-package` implies that either the `soapfish` directory is not a python package (missing `__init__.py`) or there is a misconfiguration of with `PYTHONPATH`.

The links to the WSDL and traceback have expired. Are you still encountering this issue @gudddu? If not, we should close this issue as I cannot reproduce this.

**Comment by FelixSchwarz** [comment] 2016-03-13 20:42
@gudddu Unfortunately I don't have enough information so I can't fix this issue. Feel free to reopen if you can provide the necessary information and sorry it took us so long for coming back to you.

**Closed by FelixSchwarz** 2016-03-13 20:42 UTC
Labels: waiting for additional information
