### ISSUE TITLE
wsdl2py fails if 'operation' element has no 'output' child element

### ISSUE THREAD

**Issue by madsweitling** [FelixSchwarz/soapfish#81] opened 2016-02-24 11:37 UTC
When running the following, an exception is raised in `soapfish.wsdl12.Operation.get_OutputMessage`:

```
mads@work:~/test$ wsdl2py -s minimal.wsdl 
Traceback (most recent call last):
  File "/home/mads/.virtualenvs/hvitserk/bin/wsdl2py", line 9, in <module>
    load_entry_point('soapfish==0.6.dev0', 'console_scripts', 'wsdl2py')()
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/soapfish/wsdl2py.py", line 112, in main
    code = generate_code_from_wsdl(xml, target, opt.use_wsa, cwd=cwd)
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/soapfish/wsdl2py.py", line 84, in generate_code_from_wsdl
    use_wsa=use_wsa,
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/soapfish/templates/wsdl", line 41, in top-level template code
    {%- set outputMessage = operation.get_OutputMessage() -%}
  File "/home/mads/.virtualenvs/hvitserk/local/lib/python2.7/site-packages/soapfish/wsdl11.py", line 99, in get_OutputMessage
    messageName = portTypeOperation.output.message
AttributeError: 'NoneType' object has no attribute 'message'
```

[minimal.wsdl](https://github.com/FelixSchwarz/soapfish/files/144479/minimal.wsdl.txt)

**Comment by FelixSchwarz** [comment] 2016-02-24 12:08
Thank you very much for reporting the issue. I can reproduce this. One thing I have to double check is if this is a valid WSDL (is "output" optional?). You could help me here by looking for  some spec and/or suggest a fix.

**Comment by madsweitling** [comment] 2016-02-24 13:46
I'm not too sure myself :) But the original WSDL file loads in Eclipse and Wizdler (Chrome extension). Validating `minimal.wsdl` against `validwsdl.com` gives no errors.
Validating `minimal.wsdl` against `wsdl-analyzer.com` gives an (unrelated?) error regarding the `use` attribute on the `soap12:body` child element. See http://www.wsdl-analyzer.com/service/service/1807005354?version=1

**Comment by FelixSchwarz** [comment] 2016-03-13 20:54
@madsweitling I just checked and I think your WSDL is correct ( https://www.w3.org/TR/wsdl#_one-way ). I don't have much time available right now. Can you work around the problem locally right now?

**Comment by pope1ni** [comment] 2016-03-21 15:30
I have been working on a lot of fixes and this one should be solved in my [improvements](https://github.com/flightdataservices/soapfish/tree/improvements) branch by the commit range [fe05c22...1dff9fd](https://github.com/flightdataservices/soapfish/compare/fe05c22...1dff9fd). I still have a few more things to finish before I submit a pull request.

**Comment by madsweitling** [comment] 2016-03-29 08:00
@FelixSchwarz I'm working around the issue locally.
@pope1ni Thanks for your fixes, I'll see if I can try them out with my offending WSDL.

**Comment by madsweitling** [comment] 2016-03-29 08:46
@pope1ni I gave your improvements branch a spin, however I'm getting a different exception using the same minimal.wsdl posted earlier. I get the same exception when trying the original offending WSDL file.

    (.venv)mads@work:~/github/soapfish-improvements$ python -m soapfish.wsdl2py -s ~/minimal.wsdl                                                                                                 
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/mads/github/soapfish-improvements/soapfish/wsdl2py.py", line 93, in <module>
        main()
      File "/home/mads/github/soapfish-improvements/soapfish/wsdl2py.py", line 84, in main
        code = generate_code_from_wsdl(xml, target, opt.use_wsa, cwd=cwd)
      File "/home/mads/github/soapfish-improvements/soapfish/wsdl2py.py", line 56, in generate_code_from_wsdl
        use_wsa=use_wsa,
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "soapfish/templates/wsdl", line 32, in top-level template code
        def {{ operation.name }}(request, {{ _im.part.element|remove_namespace }}):
      File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 397, in getattr
        return getattr(obj, attribute)
      File "soapfish/wsdl11.py", line 67, in part
        raise ValueError('expected exactly one part', self.name, self.parts)
    ValueError: ('expected exactly one part', 'operationRequest', [<soapfish.wsdl12.Part object at 0x7fd93aac6910>, <soapfish.wsdl12.Part object at 0x7fd93aac6950>])

**Comment by pope1ni** [comment] 2016-04-05 13:23
Right. So I have solved the issue raised in the original report in my branch as mentioned. What you are seeing now is a bug being tracked in #75. The `ValueError` was introduced in e04a585. Before this commit only a single `<wsdl:part>` element was supported in soapfish and after some areas of the code were corrected to support multiple elements, but the support for it is incomplete.

**Comment by madsweitling** [comment] 2016-04-05 15:27
@pope1ni You are right, I'm seeing #75 now. @FelixSchwarz Feel free to close this bug since it's probably a duplicate of #75 now.

**Comment by FelixSchwarz** [comment] 2016-04-05 15:54
@madsweitling you could do it yourself :-)

closing as duplicate of #75 as per comments above.

**Closed by FelixSchwarz** 2016-04-05 15:54 UTC
Labels: bug, patch-pending
